baseurl = "https://blog.kulman.sk"
languageCode = "en-us"
title = "Igor Kulman"
theme = "beautifulhugo"
Paginate = 10
disqusShortname = "coudingjournal"

[params]
  twitterName = "igorkulman"
  githubName = "igorkulman"
  subtitle = "Adventures in the world of Swift and iOS, reminiscing about the days of C#, F# and Windows development"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  blogTitle = "Coding Journal"
  readingTime = true

[Author]
  name = "Igor Kulman"
  email = "igor@kulman.sk"
  github = "igorkulman"
  twitter = "igorkulman"
  instagram = "igorkulman"
  stackoverflow = "users/581164/igor-kulman"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

[[menu.main]]
    name = "About me / contact"
    url = "/about/"
    weight = 3

[related]
threshold = 80
includeNewer = true
toLower = true

[[related.indices]]
name = "keywords"
weight = 150
[[related.indices]]
name  = "tags"
weight = 100
 