baseurl = "https://blog.kulman.sk"
languageCode = "en-us"
title = "Igor Kulman"
theme = "hugo-paper"
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  post = "/:slug/"

[params]
  github = "igorkulman"
  rss = true
  comments = false
  showRelatedPosts = true
  color = 'light'
  mastodon = "https://hachyderm.io/@igorkulman"
  avatar = "https://blog.kulman.sk/images/avatar.jpg"
  name = 'Coding Journal'
  bio = 'iOS & Swift developer. Open source fan. Building privacy-first apps and sharing what I learn.'
  disableHLJS = true

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Apps"
    url = "https://apps.kulman.sk"
    weight = 2

[related]
threshold = 80
includeNewer = true
toLower = true

[[related.indices]]
name = "keywords"
weight = 150
[[related.indices]]
name  = "tags"
weight = 100
