baseurl = "https://blog.kulman.sk"
languageCode = "en-us"
title = "Igor Kulman"
theme = "beautifulhugo"
Paginate = 5
disqusShortname = "coudingjournal"
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  post = "/:slug/"

[params]
  twitterName = "igorkulman"
  githubName = "igorkulman"
  subtitle = "Adventures in the world of Swift and iOS, reminiscing about the days of C#, F# and Windows development"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  logo = "images/avatar-icon.png"
  favicon = "favicon.ico"
  blogTitle = "Coding Journal"
  readingTime = true
  delayDisqus = true
  showRelatedPosts = true
  since = 2012
  selfHosted = true

[Author]
  name = "Igor Kulman"
  email = "igor@kulman.sk"
  github = "igorkulman"
  twitter = "igorkulman"
  stackoverflow = "users/581164/igor-kulman"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About me"
    url = "/about/"
    weight = 3

[related]
threshold = 80
includeNewer = true
toLower = true

[[related.indices]]
name = "keywords"
weight = 150
[[related.indices]]
name  = "tags"
weight = 100
 
