[context.production]
  command = "hugo --baseURL=$URL"
  [context.production.environment]
	HUGO_VERSION = "0.52"

[context.deploy-preview]
  command = "hugo --buildDrafts --buildFuture --baseURL=$DEPLOY_PRIME_URL"
  [context.deploy-preview.environment]
	HUGO_VERSION = "0.52"